spring.application.name=smartfarm
spring.datasource.url=jdbc:postgresql://localhost:5432/smartfarmdev
spring.datasource.username=postgres
spring.datasource.password=p4ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=3600000

# Logging configuration
logging.file.name=logs/smartfarm.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

storage.location=uploads
base.url=http://localhost:8080

# Mailtrap Configuration
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=your_mailtrap_username
spring.mail.password=your_mailtrap_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

smartfarm.aes.secret=Indonesia@2025Indonesia@20251212
